#ifndef CONFIG_H
#define CONFIG_H

#define PIZZAOS_TOTAL_INTERRUPTS 256

#define KERNEL_CODE_SELECTOR 0x08
#define KERNEL_DATA_SELECTOR 0x10
#define PIZZAOS_MAX_ISR80H_COMMANDS 1024

//100mb heap size
#define PIZZAOS_HEAP_SIZE_BYTES 104857600
#define PIZZAOS_HEAP_BLOCK_SIZE 4096
#define PIZZAOS_HEAP_ADDRESS 0x01000000 
#define PIZZAOS_HEAP_TABLE_ADDRESS 0x00007E00


#define PIZZAOS_SECTOR_SIZE 512
#define PIZZAOS_SECTOR_TYPE 512

#define PIZZAOS_MAX_FILESYSTEMS 12
#define PIZZAOS_MAX_FILE_DESCRIPTORS 512

#define PIZZAOS_MAX_PATH 108
#define PIZZAOS_TOTAL_GDT_SEGMENTS 6

#define PIZZAOS_PROGRAM_VIRTUAL_ADDRESS 0x400000
#define PIZZAOS_USER_PROGRAM_STACK_SIZE 1024 * 16

#define PIZZAOS_PROGRAM_VIRTUAL_STACK_ADDRESS_START 0x3FF000
#define PIZZAOS_PROGRAM_VIRTUAL_STACK_ADDRESS_END PIZZAOS_PROGRAM_VIRTUAL_ADDRESS_START - PIZZAOS_USER_PROGRAM_STACK_SIZE

#define USER_DATA_SEGMENT 0x23
#define USER_CODE_SEGMENT 0x1b


#define PIZZAOS_MAX_PROGRAM_ALLOCATIONS 1024
#define PIZZAOS_MAX_PROCESSES 12

#endif